server:
  port: 8511
spring:
  application:
    name: ppsg-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称