server:
  port: 8511
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ppsg?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10
      max-request-size: 10
  application:
    name: ppsg-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ming.ppsg.server.entity