server:
  port: 8080
spring:
  application:
    name: ppsg-zuul
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
zuul:
#  prefix: /v1
  routes:
    ribbon:
      path: /auth/**
      serviceId: ppsg-client
    feign:
      path: /admin/**
      serviceId: ppsg-client
#    auth:
#      path: /auth/**
#      serviceId: ppsg-client
#      sensitiveHeaders: Cookie,Set-Cookie
#      stripPrefix: false
#    admin:
#      path: /admin/**
#      serviceId: ppsg-client
#    user:
#      path: /user/**
#      serviceId: ppsg-client
#    guest:
#      path: /guest/**
#      serviceId: ppsg-client
