server:
  port: 8080
spring:
  application:
    name: ppsg-zuul
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
#  prefix: /v1
  routes:
    auth:
      path: /auth/**
      serviceId: ppsg-client
    admin:
      path: /admin/**
      serviceId: ppsg-admin
#    auth:
#      path: /auth/**
#      serviceId: ppsg-client
#      sensitiveHeaders: Cookie,Set-Cookie
#      stripPrefix: false
#    admin:
#      path: /admin/**
#      serviceId: ppsg-client
#    user:
#      path: /user/**
#      serviceId: ppsg-client
#    guest:
#      path: /guest/**
#      serviceId: ppsg-client


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: false