CREATE TABLE `p_config_combat` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`code` VARCHAR(32)  DEFAULT NULL  COMMENT '',
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`combat` INT(11)  DEFAULT NULL  COMMENT '战力',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

