CREATE TABLE `p_config_star` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`code` VARCHAR(32)  DEFAULT NULL  COMMENT '1,2,3,4,5',
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '白,黑,银,金,钻',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

